import { Link } from "react-router";

const principles = ["Materiales con certificación internacional", "Niveles de blindaje de acuerdo con cada necesidad", "Procesos supervisados bajo normas de calidad", "Mantenimiento especializado para prolongar la protección"];

export function CenturBlindajesPage() {
  return <main className="bg-[#161719]">
    <section className="relative isolate min-h-[calc(100svh-68px)] overflow-hidden"><img src="/images/centur/hero-seguridad.png" alt="Unidad protegida en una llegada privada" className="absolute inset-0 -z-20 size-full object-cover" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(12,13,15,.94),rgba(12,13,15,.56)_45%,rgba(12,13,15,.08))]" /><div className="absolute -bottom-40 -left-32 -z-10 size-[34rem] border border-white/15" /><div className="mx-auto flex min-h-[calc(100svh-68px)] max-w-[1400px] items-end px-5 pb-16 pt-24 sm:px-8 lg:items-center lg:pb-8"><div className="max-w-3xl"><img src="/centur/logotipo-centur.svg" alt="CENTUR Blindajes" className="max-h-16 max-w-64 brightness-0 invert" /><h1 className="mt-10 text-[clamp(2.6rem,5vw,5rem)] font-bold leading-[.96] tracking-[-.07em]">Seguridad vehicular diseñada con precisión.</h1><p className="mt-7 max-w-xl leading-8 text-white/75">Más de 20 años de experiencia en blindaje automotriz, combinando tecnología, trabajo especializado y cuidado por el diseño original de cada unidad.</p><Link to="/contacto" className="mt-9 inline-flex rounded-full border border-white/35 px-5 py-3 text-sm font-semibold hover:bg-white hover:text-[#161719]">Solicitar asesoría</Link></div></div></section>
    <section className="mx-auto grid max-w-[1400px] gap-10 px-5 py-28 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><h2 className="text-4xl font-bold leading-tight tracking-[-.06em]">Protección hecha a la medida.</h2><div className="max-w-2xl space-y-6 leading-8 text-white/70"><p>CENTUR desarrolla vehículos protegidos con materiales de alta calidad y certificación internacional, buscando ofrecer seguridad sin comprometer prestaciones ni carácter.</p><p>La configuración se plantea según las necesidades de cada persona: nivel de protección, tipo de unidad y un servicio que acompaña también después de la entrega.</p></div></section>
    <section className="border-y border-white/15 bg-[#1d1e20]"><div className="mx-auto grid max-w-[1400px] gap-x-12 px-5 py-12 sm:px-8 md:grid-cols-2">{principles.map((principle, index) => <p key={principle} className="border-t border-white/30 py-5 text-lg"><span className="mr-3 text-white/40">0{index + 1}</span>{principle}</p>)}</div></section>
  </main>;
}
