import { Link } from "react-router";

const principles = ["Criterio para cada decisión", "Especialidades que se complementan", "Atención clara durante el proceso"];

export function NosotrosPage() {
  return <div>
    <section className="relative isolate min-h-[calc(100svh-68px)] overflow-hidden"><img src="/images/grupo-egd/hero-nosotros-taller.png" alt="Equipo de especialistas junto a un vehículo en taller" className="absolute inset-0 -z-20 size-full object-cover object-[62%_center]" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(7,11,18,.96),rgba(7,11,18,.65)_52%,rgba(7,11,18,.16))]" /><div className="mx-auto flex min-h-[calc(100svh-68px)] max-w-[1400px] items-end px-5 pb-16 pt-24 sm:px-8 lg:items-center lg:pb-8"><div className="max-w-4xl"><p className="text-sm text-white/65">Grupo EGD</p><h1 className="mt-5 text-[clamp(2.8rem,5.5vw,5.8rem)] font-semibold leading-[.93] tracking-[-.08em]">Una visión que conecta cada decisión automotriz.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">Reunimos especialidades para acompañar la búsqueda, adquisición, conservación y protección de un vehículo con atención a lo que cada etapa requiere.</p></div></div></section>
    <section className="border-y border-white/10 bg-[#16171b]"><div className="mx-auto grid max-w-[1400px] gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[.85fr_1.15fr]"><h2 className="text-4xl font-semibold leading-tight tracking-[-.065em]">El valor está en la conexión entre especialidades.</h2><div className="max-w-2xl space-y-6 leading-8 text-white/65"><p>Grupo EGD reúne empresas enfocadas en compra y venta, cuidado posterior, movilidad y seguridad vehicular. Cada una atiende una necesidad concreta y aporta conocimiento propio al recorrido de cada cliente.</p><p>La visión compartida es sencilla: escuchar primero, explicar con claridad y proponer una solución que responda a la unidad, al momento y a las prioridades de quien la conduce.</p></div></div></section>
    <section className="mx-auto grid max-w-[1400px] gap-3 px-5 py-28 sm:px-8 md:grid-cols-[1.2fr_.8fr]"><img src="/enlace-egd/imgs/4.0.png" alt="Automóvil seleccionado" className="aspect-[4/5] w-full rounded-2xl object-cover" /><div className="relative overflow-hidden rounded-2xl border border-white/15 p-8 sm:p-10"><h2 className="relative text-3xl font-semibold tracking-[-.06em]">Una relación de largo plazo.</h2><p className="relative mt-8 leading-8 text-white/60">Desde elegir una unidad hasta protegerla, mantenerla y conservar su apariencia, el grupo busca que las decisiones posteriores se sientan tan bien acompañadas como la primera.</p><ul className="relative mt-12 space-y-4 border-t border-white/15 pt-6">{principles.map((principle, index) => <li key={principle} className="flex gap-3 text-sm text-white/70"><span className="text-white/35">0{index + 1}</span>{principle}</li>)}</ul><Link className="relative mt-12 inline-block rounded-full border border-white/25 px-4 py-2 text-sm hover:bg-white hover:text-[#101113]" to="/empresas">Conocer las empresas</Link></div></section>
  </div>;
}
