import { Link } from "react-router";

const services = [["Protección XPEL", "PPF, recubrimiento cerámico, polarizado premium y protección para parabrisas: soluciones enfocadas en conservar la apariencia y el valor del vehículo."], ["Lavado y detallado", "Lavado premium, detallado interior y exterior, corrección de pintura y descontaminado para recuperar limpieza, profundidad y uniformidad en los acabados."], ["Mecánica y diagnóstico", "Servicio menor y mayor, diagnóstico especializado y atención mecánica para sostener el desempeño, la seguridad y la durabilidad de cada unidad."], ["Restauración estética", "Hojalatería, pintura y reemplazo de calipers para resolver detalles puntuales sin perder de vista el conjunto del vehículo."]];

export function EgdAftersalePage() {
  return <main className="bg-[#0c2447]">
    <section className="relative isolate min-h-[calc(100svh-68px)] overflow-hidden"><img src="/images/egd-aftersale/detalle-en-proceso.png" alt="Cuidado especializado sobre la carrocería de un automóvil" className="absolute inset-0 -z-20 size-full object-cover" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(7,29,62,.96),rgba(7,29,62,.68)_47%,rgba(7,29,62,.12))]" /><div className="mx-auto flex min-h-[calc(100svh-68px)] max-w-[1400px] items-end px-5 pb-16 pt-24 sm:px-8 lg:items-center lg:pb-8"><div className="max-w-3xl"><img src="/egd-aftersale/logotipo-egd-aftersale.svg" alt="EGD Aftersale & Detailing Center" className="max-h-14 max-w-72 brightness-0 invert" /><h1 className="mt-10 text-[clamp(2.6rem,5vw,5rem)] font-bold leading-[.96] tracking-[-.07em]">Cuidado técnico para que cada detalle se mantenga en su lugar.</h1><p className="mt-7 max-w-xl leading-8 text-white/75">El cuidado posterior de un vehículo se define en los procesos, materiales y manos que intervienen. Aquí, cada servicio busca extender su mejor versión.</p></div></div></section>
    <section className="mx-auto grid max-w-[1400px] gap-8 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><h2 className="text-4xl font-bold tracking-[-.06em]">Un centro para conservar lo que valoras.</h2><p className="max-w-2xl leading-8 text-white/70">Desde una atención estética puntual hasta el mantenimiento que da continuidad a la experiencia de manejo, EGD Aftersale & Detailing Center integra soluciones para vehículos que requieren precisión y seguimiento.</p></section>
    <section className="border-y border-white/15"><div className="mx-auto max-w-[1400px] px-5 py-8 sm:px-8">{services.map(([title, body], index) => <article key={title} className="grid gap-6 border-b border-white/15 py-9 last:border-0 md:grid-cols-[.7fr_1.3fr]"><p className="text-2xl font-bold tracking-[-.05em]">0{index + 1} — {title}</p><p className="max-w-xl leading-8 text-white/65">{body}</p></article>)}</div></section>
    <section className="mx-auto max-w-[1400px] px-5 py-24 sm:px-8"><Link to="/contacto" className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#0c2447]">Agenda una cita</Link></section>
  </main>;
}
